import { Toaster } from "react-hot-toast";
import Footer from "./components/Footer";
import Navbar from "./components/Navbar";
import "./globals.css";
import { cookies } from "next/headers";
import { CartProvider } from "./context/CartContext";

export const metadata = {
  title: "Shopery E-Commerce",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const cookieStore = await cookies();
  const token = await cookieStore.get("token")?.value;

  return (
    <html>
      <head>
        <link
          rel="icon"
          href="/icon?<generated>"
          type="image/<generated>"
          sizes="<generated>"
        />
      </head>
      <body>
        <Toaster position="top-center" reverseOrder={false} />
        <CartProvider>
          <Navbar token={token} />
          {children}
          <Footer />
        </CartProvider>
      </body>
    </html>
  );
}
